version: '3.4'

services:
  moviecatalog-database:
    container_name: moviecatalog-database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - moviecatalog-data:/data/db

  ordering-database:
    container_name: ordering-database
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=OrderingDatabase
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ordering-data:/var/lib/postgressql/data/
      
  blazor-webapp:
    container_name: blazor-webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - moviecatalog-api
      - shoppingcart-cache
      - ordering-api
    ports:
      - "7100:80"

  moviecatalog-api:
    container_name: moviecatalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MovieCatalogDatabase__ConnectionString=mongodb://moviecatalog-database:27017"
    depends_on:
      - moviecatalog-database
    ports:
      - "7101:80"

  shoppingcart-api:
    container_name: shoppingcart-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingCartCache__ConnectionString=shoppingcart-cache:6379"
    depends_on:
      - shoppingcart-cache
    ports:
      - "7102:80"

  ordering-api:
    container_name: ordering-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "OrderingDatabase__ConnectionString=Server=ordering-database;Port=5432;Database=OrderingDatabase;User Id=postgres;Password=test;"
    depends_on:
      - ordering-database
    ports:
      - "7103:80"

  ordering-database-pgadmin:
    container_name: ordering-database-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin-data:/root/.pgadmin

volumes:
  moviecatalog-data:
    external: false
  ordering-data:
    external: false
  pgadmin-data:
    external: false