version: '3.4'

services:
  moviecatalog-database:
    image: mongo

  shoppingcart-cache:
    image: redis

  ordering-database:
    image: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  blazor-webapp:
    image: ${DOCKER_REGISTRY-}blazorwebapp
    build:
      context: .
      dockerfile: WebApps/BlazorWebApp/Dockerfile

  moviecatalog-api:
    image: ${DOCKER_REGISTRY-}moviecatalogapi
    build:
      context: .
      dockerfile: Services/MovieCatalog.API/Dockerfile

  shoppingcart-api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: Services/ShoppingCart.API/Dockerfile

  ordering-api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering.API/Dockerfile

  ordering-database-pgadmin:
    image: dpage/pgadmin4